### ISSUE TITLE
instructions: "ANDQ imm64 r64" and "MOVD r32   xmm" unsupported

### ISSUE THREAD

**Issue by samuel** [mmcloughlin/avo#50] opened 2019-01-14 05:20 UTC
The go assembler supports both of the following instructions but avo does not.
- ANDQ imm64, r64
- MOVD r32, xmm

I see that x86/zctors.go is autogenerated, but I'm a bit lost on how to update the generator to resolve this. To make sure that valid output would be generated I modified it by hand and the generated code was properly assembled:

```
diff --git a/x86/zctors.go b/x86/zctors.go
index 6d03480..f52ba55 100644
--- a/x86/zctors.go
+++ b/x86/zctors.go
@@ -1280,6 +1280,7 @@ func ANDPS(mx, x operand.Op) (*intrep.Instruction, error) {
 // 	ANDQ imm32 rax
 // 	ANDQ imm8  r64
 // 	ANDQ imm32 r64
+// 	ANDQ imm64 r64
 // 	ANDQ r64   r64
 // 	ANDQ m64   r64
 // 	ANDQ imm8  m64
@@ -1308,6 +1309,13 @@ func ANDQ(imr, mr operand.Op) (*intrep.Instruction, error) {
 			Inputs:   []operand.Op{mr},
 			Outputs:  []operand.Op{mr},
 		}, nil
+	case operand.IsIMM64(imr) && operand.IsR64(mr):
+		return &intrep.Instruction{
+			Opcode:   "ANDQ",
+			Operands: []operand.Op{imr, mr},
+			Inputs:   []operand.Op{mr},
+			Outputs:  []operand.Op{mr},
+		}, nil
 	case operand.IsR64(imr) && operand.IsR64(mr):
 		return &intrep.Instruction{
 			Opcode:   "ANDQ",
@@ -8450,6 +8458,7 @@ func MOVBWZX(mr, r operand.Op) (*intrep.Instruction, error) {
 // 	MOVD imm32 m64
 // 	MOVD r64   m64
 // 	MOVD xmm   r64
+// 	MOVD r32   xmm
 // 	MOVD r64   xmm
 // 	MOVD xmm   xmm
 // 	MOVD m64   xmm
@@ -8505,6 +8514,13 @@ func MOVD(imrx, mrx operand.Op) (*intrep.Instruction, error) {
 			Inputs:   []operand.Op{imrx},
 			Outputs:  []operand.Op{mrx},
 		}, nil
+	case operand.IsR32(imrx) && operand.IsXMM(mrx):
+		return &intrep.Instruction{
+			Opcode:   "MOVD",
+			Operands: []operand.Op{imrx, mrx},
+			Inputs:   []operand.Op{imrx},
+			Outputs:  []operand.Op{mrx},
+		}, nil
 	case operand.IsR64(imrx) && operand.IsXMM(mrx):
 		return &intrep.Instruction{
 			Opcode:   "MOVD",
```

**Comment by mmcloughlin** [comment] 2019-01-14 16:18
Thank you for reporting this issue!

Unfortunately I am not entirely surprised to find some instruction forms are missing. My testing thus far has focussed on ensuring the instructions in the `avo` database are valid according to the Go assembler, not that the database contains _all_ Go assembler instructions.

For background, the database is formed by merging the x86 csv from golang.org/x/arch/x86 with the PeachPy Opcodes database. The raw datafiles are in [internal/data](https://github.com/mmcloughlin/avo/tree/master/internal/data). The ugly code to merge these datasources and fix up special cases is in [internal/load](https://github.com/mmcloughlin/avo/tree/master/internal/load). This is used to "bootstrap" the canonical `avo` instruction database [internal/inst](https://github.com/mmcloughlin/avo/tree/master/internal/inst), which drives the [internal/avogen](https://github.com/mmcloughlin/avo/tree/master/internal/cmd/avogen) code generator. (See #23 and #22 for more).

So to diagnose this problem we'll need to look at the underlying datafiles. If the instructions are present it may be something to do with the loading.

**Comment by mmcloughlin** [comment] 2019-01-15 01:05
Regarding `ANDQ`, are you sure?

The following assembles:

```
$ cat asm.s
TEXT ·And(SB), $0
	ANDQ $(1<<31), AX
$ go tool asm asm.s
```

If I change the constant:

```
$ cat asm.s
TEXT ·And(SB), $0
	ANDQ $(1<<53), AX
$ go tool asm asm.s
asm: invalid instruction: 00000 (asm.s:2)	ANDQ	$9007199254740992, AX
asm: assembly failed
```

**Comment by dgryski** [comment] 2019-01-15 01:31
What does the Intel instruction list say?

**Comment by samuel** [comment] 2019-01-15 01:41
Yeah, you're right. I was confused by the disassembler showing a sign-extended version at a full 64-bit even though the actual immediate cannot be 64-bit. Sorry for that.

I was translating from existing Go assembly of `ANDQ $(~15), AX` which was showing up as `and rax, 0xfffffffffffffff0` in the disassembler though it's actually just encoded as an 8-bit value sign-extended to 64-bit 🤦‍♂️`48 83 E0 F0`

To get the same result I need to do `ANDQ(U32(^uint32(15)), n)` which is functionally the same but uses a 32-bit value instead of 8-bit. If I try `ANDQ(U8(^uint8(15)), n)` then the generated assembly is `ANDQ   $0xf0, BP` which isn't right in this case as the Go assembler treats it as a 32-bit value. Not sure there's an easy solution though since it's more of heuristic on the Go assembler on which instruction to encode as (`$(~15)` it seems to understand the intent) or if it matters too much from a cycles perspective if it's 8-bit sign extended or 32-bit.

**Comment by mmcloughlin** [comment] 2019-01-15 01:44
> What does the Intel instruction list say?

According to the manual it only accepts `imm32`.

https://www.felixcloutier.com/x86/and

However I wanted to check it directly with the `go` assembler because I know it pulls a few tricks to pretend things like this work when they are actually not real instructions. For example, the Go assembler accepts a floating point immediate to `ADDSD`. [Under the hood](https://github.com/golang/go/blob/50bd1c4d4eb4fac8ddeb5f063c099daccfb71b26/src/cmd/internal/obj/x86/obj6.go#L265-L286) it will create a 64-bit data value and pass a memory argument. Given this kind of behavior, I would not have been surprised if the Go assembler would pretend to you that `ANDQ` accepts a 64-bit immediate when actually it is passed in memory.

**Comment by mmcloughlin** [comment] 2019-01-15 01:47
`MOVD` is declared as an alias for `MOVQ` in my favorite "Annoying aliases" list:

https://github.com/golang/go/blob/462e90259af39af9e23c9d919e002913042c2faa/src/cmd/asm/internal/arch/arch.go#L174

Is it possible you want `MOVL`? I can dig into this more, but that's my first thought, since Go usually uses the `L` suffix for 32-bit instructions.

**Comment by samuel** [comment] 2019-01-15 19:04
Go assembler seems to accept MOVL and MOVD for r32 → xmm though Intel's assembly generally just has MOVD for xmm (SSE2) registers and VMOVD for xmm1 (AVX). So I had MOVL originally in the Go assembly but avo doesn't support xmm registers for it so tried MOVD to match Intel. I'm pretty inexperienced with 86-64 assembly though (let alone Go's version of the assembly) so as with my mistake with ANDQ quite likely I'm missing how I should be doing this. Thanks for helping with this issue.

https://www.felixcloutier.com/x86/movd:movq

**Comment by mmcloughlin** [comment] 2019-01-16 23:55
@samuel I appreciate you debugging this with me. I am convinced there is a problem here, I just need to find the time to dig in and fix it. Probably this weekend; unfortunately `avo` isn't my day job haha.

**Comment by mmcloughlin** [comment] 2019-01-20 03:10
Go defines `MOVQ` as a mix of the `MOVD`/`MOVQ` (and `MOVDQ2Q`?) instructions.

https://github.com/golang/go/blob/5538a9a34fc4e395967c0233aab5bdde0cebbf9b/src/cmd/internal/obj/x86/asm6.go#L477-L496

```go
var ymovq = []ytab{
	// valid in 32-bit mode
	{Zm_r_xm_nr, 1, argList{Ym, Ymr}},  // 0x6f MMX MOVQ (shorter encoding)
	{Zr_m_xm_nr, 1, argList{Ymr, Ym}},  // 0x7f MMX MOVQ
	{Zm_r_xm_nr, 2, argList{Yxr, Ymr}}, // Pf2, 0xd6 MOVDQ2Q
	{Zm_r_xm_nr, 2, argList{Yxm, Yxr}}, // Pf3, 0x7e MOVQ xmm1/m64 -> xmm2
	{Zr_m_xm_nr, 2, argList{Yxr, Yxm}}, // Pe, 0xd6 MOVQ xmm1 -> xmm2/m64


	// valid only in 64-bit mode, usually with 64-bit prefix
	{Zr_m, 1, argList{Yrl, Yml}},      // 0x89
	{Zm_r, 1, argList{Yml, Yrl}},      // 0x8b
	{Zilo_m, 2, argList{Ys32, Yrl}},   // 32 bit signed 0xc7,(0)
	{Ziq_rp, 1, argList{Yi64, Yrl}},   // 0xb8 -- 32/64 bit immediate
	{Zilo_m, 2, argList{Yi32, Yml}},   // 0xc7,(0)
	{Zm_r_xm, 1, argList{Ymm, Ymr}},   // 0x6e MMX MOVD
	{Zr_m_xm, 1, argList{Ymr, Ymm}},   // 0x7e MMX MOVD
	{Zm_r_xm, 2, argList{Yml, Yxr}},   // Pe, 0x6e MOVD xmm load
	{Zr_m_xm, 2, argList{Yxr, Yml}},   // Pe, 0x7e MOVD xmm store
	{Zaut_r, 1, argList{Yiauto, Yrl}}, // 0 built-in LEAQ
}
```

The `avo` database is broken because:

* I loaded the definition of `MOVQ` from the Opcodes database (see [internal/data](https://github.com/mmcloughlin/avo/tree/master/internal/data)). I have not confirmed but this _should_ agree with the intel definition
* I do process the "annoying aliases" list (see [internal/load/zannoyingaliases.go](https://github.com/mmcloughlin/avo/blob/master/internal/load/zannoyingaliases.go)), however all I do is define the alias as a copy of the target instruction
* In this case the correct behavior when processing an alias would have been to _merge_ the instruction forms

Let me see if this is true of the other aliases too.

**Comment by mmcloughlin** [comment] 2019-01-21 06:36
@samuel I think this is now fixed. Please let me know if it works for you.

**Comment by mmcloughlin** [comment] 2019-01-21 07:16
Third build failure in a row. This is embarrassing! Interestingly the last one is because although the assembler will accept `MOVQ r32 xmm`, `go vet` doesn't like it. Makes sense.

**Comment by mmcloughlin** [comment] 2019-01-22 06:52
I think this is resolved. Please do reopen if you continue to have this problem.

Thanks again for reporting the issue, I'm looking forward to seeing what you're doing with `avo` :)

**Closed by mmcloughlin** 2019-01-22 06:52 UTC
Labels: instructions

**Comment by bwesterb** [comment] 2020-05-07 12:33
I still seem to hit this issue.  To get an `AND` with an 64b immediate using avo, I have to load it in a register first:

```go
func and_imm64(c uint64, inout Op) {                                             
    tmp := GP64()                                                                
    MOVQ(U64(c), tmp)                                                            
    ANDQ(tmp, inout)                                                             
}
```

which is not ideal.

**Comment by mmcloughlin** [comment] 2020-05-07 20:28
@bwesterb I don't think there is an `AND` instruction taking a 64-bit immediate.

https://www.felixcloutier.com/x86/and

Is your immediate value `c` a full 64-bit value? `ANDQ` will sign extend a 32-bit immediate to 64 bits, so that could work for smaller values of `c`. Otherwise you have to do the `MOVQ`.

**Comment by bwesterb** [comment] 2020-05-08 11:48
Sorry, you're right — I was mistaken!
